server:
  port: 8080

spring:
  application:
    name: PlanSlot

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/planslot
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  secret: ${secret_key}
  access-token-validity-in-milliseconds: 3600000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
